### ISSUE TITLE
http://localhost:8000/index.html is not found

### ISSUE THREAD

**Issue by AlyShmahell** [Spianopolese/webpyux#3]
config.ini, index.html, and login.html are specified in .gitignore.

**Comment by Spianopolese** [comment]
There is an error in the repository due to the transfer from bitbucket to github. I solve the problem as soon as possible.
It still wasn't 100% ready I still had to make a couple of changes

**Comment by Spianopolese** [comment]
I'll update it soon

**Comment by Spianopolese** [comment]
try now!

**Comment by AlyShmahell** [comment]
great, it's solved.
