### ISSUE TITLE
hard coded routes are incompatible with common python frameworks.

### ISSUE THREAD

**Issue by AlyShmahell** [Spianopolese/webpyux#4]
Upon loading the starter example:

`"drupy/session/token" not found error` is thrown in the browser console upon trying to test the login, because it's only running with a simple `http.server`.

Constructing a simple **BottlePy** server that compensates for the route throws more errors because of the hardcoding, e.g.: `"../core"`

Changing the routes either in `index.html` or `config.ini` throws the following error (in the browser DOM, on the index page, without redirecting to the login page):

`PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 241, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 142, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 9 padding: 15px; margin: 15px;} ^ SyntaxError: invalid decimal literal`

Modifications made to reproduce the above-mentioned error:

1. replace "../core/" with "core/" in all instances inside "index.html" and "login.html".
2. replace "../assets/" with "assets/" in all instances inside "index.html" and "login.html".
3. run server.py inside the root folder (above core, assets, app), which contains the following server code:
```py
from bottle import Bottle, run, template, static_file

app = Bottle()

@app.get('/')
def index():
    return template('app/index.html')

@app.route('/drupy/rest/auth')
def index():
    return template('app/login.html')

@app.route('/drupy/rest/login')
def index():
    return template('app/login.html')

@app.get('/core/<filename:path>')
def get_static(filename):
    return static_file(filename, root='core')

@app.get('/assets/<filename:path>')
def get_static(filename):
    return static_file(filename, root='assets')

@app.get('/<filename:path>')
def get_static(filename):
    return static_file(filename, root='./app')

@app.route('drupy/session/token')
def hello():
    return "token test"

run(app, host='localhost', port=8000)
```

**Comment by giodegas** [comment]
I think routes should be agnostic, so:

    /drupy/...

shall not be allowed.

**Comment by Spianopolese** [comment]
All routes are configurable as desired.
The config.ini file in STARTER contains only placeholders used as examples.
In particular http://localhost/session/drupy/token can be any url (https://test.org/test/test1).
The important thing is that the url corresponds to a congruent response as described in the guide. For example url in pre_auth must respond with a string. 
Anyway I will update the config.ini as soon as possible by removing all urls and leaving some commented examples.

**Comment by AlyShmahell** [comment]
> All routes are configurable as desired. The config.ini file in STARTER contains only placeholders used as examples. In particular http://localhost/session/drupy/token can be any url (https://test.org/test/test1). The important thing is that the url corresponds to a congruent response as described in the guide. For example url in pre_auth must respond with a string. Anyway I will update the config.ini as soon as possible by removing all urls and leaving some commented examples.

After reading the explanation I was able to get it to start, therefore I'm closing this issue.

**Comment by giodegas** [comment]
This explaination shall be included in the User Manual.
