### ISSUE TITLE
chart.py self._type setting is erroneous. 

### ISSUE THREAD

**Issue by AlyShmahell** [Spianopolese/webpyux#6]
`self._type` inside `chart.py` is not being set correctly, take the following code snippets for example:
- setting up a chart widget entry in the menu:
```py
@app.route('/rest/menu/test', method=['get'])
@enable_cors
def test():
    return {
   "test":{
      "label":"Test Widget",
      "dataset":{
         "widget-1":{
            "label":"Dataset Test 1",
            "widgets":[
               {
                  "label":"Widget 1",
                  "class":"test",
                  "url":"/rest/menu/test/widget/1"
               },
               {
                  "label":"Widget 2",
                  "class":"test",
                  "url":"/rest/menu/test/widget/2"
               },
               {
                  "label":"Chart Widget",
                  "class":"chart",
                  "url":"/rest/menu/test/widget/chart"
               }
            ]
         }
      }
   },
   "element_no_dataset":{
     "label":"Widget no Dataset",
     "class" :"simple_test",
     "url":"/rest/menu/test/widget/3"
   }
}
```
 - and the corresponding widget callback:
```py
@app.route('/rest/menu/test/widget/chart', method=['get'])
@enable_cors
def widget4():
    return {
        "label" : "DATA" ,
            "list_view_dataset" : "DATA" ,
            "list_view_label" : "doughnut" ,
            "class" : "chart" ,
            "data" : {
                "labels" : [
                "Red" ,
                "Blue" ,
                "Yellow"
                ],
            "datasets" : [
                {
                    "label" : "chart" ,
                    "data" : [
                        300,
                        50,
                        100
                    ] ,
                    "backgroundColor" : [
                    "rgb(255, 0, 0)" ,
                    "rgb(0, 255, 0)" ,
                    "rgb(0, 0, 255)"
                    ] ,
                    "hoverOffset" : 4
                }
            ]
            } ,
            "size" : 485
    }
```
I'm assuming `"list_view_label": "doughnut"` should set the type to **"doughnut"**, but the type is being set to **"chart"** which results in an error and the chart not showing. I set it manually to **doughnut** while testing so that I can get the chart to show.

**Comment by Spianopolese** [comment]
Hi, You are right.
The initial idea was that the menu item defined the subtype of the widget. I made a mistake on the documentation.

To get around this error, I added the type (optional) and class and refactored the code.

I will update the documentation as soon as possible being careful not to make mistakes.

If you want to see how it works I'll leave you the correct rest below.

{
  "chart": {
    "label": "Chart",
    "dataset": {
      "widget-11": {
        "label": "I film più Belli di Harry Potter",
        "widgets": [
          {
            "label": "Bar Chart",
            "class": "chart",
            "type": "bar",
            "url": "http://localhost/drupy/rest/widget/11"
          },
          {
            "label": "Doughnut",
            "class": "chart",
            "type": "doughnut",
            "url": "http://localhost/drupy/rest/widget/11"
          },
          {
            "label": "Pie Chart",
            "class": "chart",
            "type": "pie",
            "url": "http://localhost/drupy/rest/widget/11"
          }
        ]
      },
      "widget-13": {
        "label": "DATA-13",
        "widgets": [
          {
            "label": "Doughnut",
            "class": "chart",
            "type": "doughnut",
            "url": "http://localhost/drupy/rest/widget/13"
          },
          {
            "label": "Pie Chart",
            "class": "chart",
            "type": "pie",
            "url": "http://localhost/drupy/rest/widget/13"
          }
        ]
      }
    }
  },
  "text": {
    "label": "Text",
    "dataset": {
      "widget-12": {
        "label": "DATA-12",
        "widgets": [
          {
            "label": "One column",
            "class": "text",
            "type": "one_column",
            "url": "http://localhost/drupy/rest/widget/12"
          },
          {
            "label": "Two Column",
            "class": "text",
            "type": "two_column",
            "url": "http://localhost/drupy/rest/widget/12"
          }
        ]
      }
    }
  }
}

However the implementation of custom widgets remains the same.

If you have any problems let me know

**Comment by Spianopolese** [comment]
I have updated the documentation. Let me know if there are any issues or parts that can be explained better.

**Comment by AlyShmahell** [comment]
Thank you, I've updated the test app accordingly.
