### ISSUE TITLE
is it possible to allow for user input in widget queries?

### ISSUE THREAD

**Issue by AlyShmahell** [Spianopolese/webpyux#7]
The documentation specifies that widget queries have the following parameters:

> A.6.5 Widget REST
> Ad ogni item di menù / widget è associato un REST url come descritto sopra. La risposta all’URL
> deve essere del tipo
> • Method: GET
> • Query parameters:
> – access_token: string
> – email: string

and the only way to specify widget entries from what I see is through:

```py
@app.route('/rest/menu/test', method=['get'])
@enable_cors
def test():
    return {
   "test":{
      "label":"Test Widget",
      "dataset":{
         "widget-1":{
            "label":"Dataset Test 1",
            "widgets":[
               {
                  "label":"Widget 1",
                  "class":"test",
                  "url":"/rest/menu/test/widget/1"
               },
               {
                  "label":"Widget 2",
                  "class":"test",
                  "url":"/rest/menu/test/widget/2"
               },
               {
                  "label":"Chart Widget",
                  "class":"chart",
                  "url":"/rest/menu/test/widget/chart"
               }
            ]
         }
      }
   },
   "element_no_dataset":{
     "label":"Widget no Dataset",
     "class" :"simple_test",
     "url":"/rest/menu/test/widget/3"
   }
}
```
is it possible to specify input elements and allow the user to send parameters with the query? if so, then how?

**Comment by Spianopolese** [comment]
Like a form? (The user enters the fields and sends the data on submit).

If the idea is like a form, currently the framework doesn't manage the sending of data.

The fact remains that you can create a widget form that does what you need.

If you give me a practical example I can see how to do it

**Comment by AlyShmahell** [comment]
Yes indeed, I meant something like a form, for example:
- The user clicks on "Chart" from the list.
- A form pops up and there's a dropdown menu & a text box.
- The user can choose the type of chart from the menu and enters the name of the dataset in the box.
- Both are sent with the Chart Widget request.
- The backend serves the appropriate dataset and widget type to the frontend.

If this is not possible I will close this issue, I just wanted to cover everything before I finish testing.

**Comment by Spianopolese** [comment]
This is the next phase of the framework, the implementation of the "New" section of the menu which will allow exactly what you wrote.

It will allow user input of any already defined widgets.

Since the graduation date is near, I don't think I can implement it completely because it requires a lot of work (like the creation of dynamic input forms based on the data types that the widget uses).

A probable implementation date I think could be during the Christmas break.

So for now no, the framework only shows widgets.

**Comment by AlyShmahell** [comment]
alright, good luck with the graduation (hopefully 110 😄).
I'm closing the issue, everything is working under the current implementation.
